FROM alpine:3.2

RUN apk --update add go

COPY . /go/src/github.com/bobrik/zoidberg

RUN export GOPATH=/go:/go/src/github.com/bobrik/zoidberg/Godeps/_workspace && \
    go get github.com/bobrik/zoidberg/...

ENTRYPOINT ["/go/bin/zoidberg"]